import re
import ezodf
import xlsxwriter
from pathlib import Path
from worker.logging_config import logger

class XlsxConverter:
    @staticmethod
    def translate_formula(formula: str) -> str:
        """
        Translates an ODS formula (which uses semicolons and dot sheet separators)
        to a standard Excel formula format compatible with MS Excel.
        """
        if not formula:
            return ""
        if not formula.startswith('='):
            return formula

        in_quotes = False
        chars = []
        for i, char in enumerate(formula):
            if char == '"':
                in_quotes = not in_quotes
            elif char == ';' and not in_quotes:
                # ODS uses semicolon separators for arguments; Excel uses commas
                chars.append(',')
                continue
            elif char == '.' and not in_quotes:
                # ODS uses SheetName.A1; Excel uses SheetName!A1
                if chars and (chars[-1].isalnum() or chars[-1] == '$'):
                    chars.append('!')
                    continue
            chars.append(char)

        res = "".join(chars)
        # Remove '$' sheet anchors which can confuse some Excel versions, e.g. $Entrada!A:B -> Entrada!A:B
        res = res.replace("$", "")
        return res

    @classmethod
    def convert_ods_to_xlsx(cls, ods_path: Path, xlsx_path: Path, fiat: str = "EUR", tax_year: int = 2025) -> bool:
        """
        Converts an ODS file generated by RP2 to a beautifully styled, formula-active Excel sheet,
        matching the exact color coordinates and fonts of the original LibreOffice ODS reports.
        """
        if not ods_path.exists():
            logger.error("Source ODS file not found: {}", ods_path)
            return False

        logger.info("Converting ODS to styled Excel matching LibreOffice layout: {}", ods_path.name)
        try:
            doc = ezodf.opendoc(str(ods_path))
            workbook = xlsxwriter.Workbook(str(xlsx_path))

            # --- Font Definition ---
            font_name = "Arial"

            # --- Style Formats Library ---
            # Common Table Header (Medium Gray)
            gray_header_format = workbook.add_format({
                'font_name': font_name, 'font_size': 10, 'bold': True,
                'font_color': '#000000', 'bg_color': '#B2B2B2',
                'align': 'center', 'valign': 'vcenter', 'border': 1, 'border_color': '#7F7F7F'
            })

            # Special Input Column Header (Soft Yellow)
            yellow_header_format = workbook.add_format({
                'font_name': font_name, 'font_size': 10, 'bold': True,
                'font_color': '#000000', 'bg_color': '#FFFFA6',
                'align': 'center', 'valign': 'vcenter', 'border': 1, 'border_color': '#7F7F7F'
            })

            # Base style options for data cells
            base_style = {'font_name': font_name, 'font_size': 10, 'valign': 'vcenter', 'border': 1, 'border_color': '#7F7F7F'}
            bold_style = {**base_style, 'bold': True}

            # Standard cell (White background)
            cell_format = workbook.add_format({**base_style, 'bg_color': '#FFFFFF'})
            bold_cell_format = workbook.add_format({**bold_style, 'bg_color': '#FFFFFF'})

            # Sheet Title Block (Row 0 or 1, big bold title)
            title_format = workbook.add_format({
                'font_name': font_name, 'font_size': 16, 'bold': True, 'font_color': '#000000', 'valign': 'vcenter'
            })
            subtitle_format = workbook.add_format({
                'font_name': font_name, 'font_size': 11, 'bold': True, 'font_color': '#000000', 'valign': 'vcenter'
            })

            # Pricing Highlight Color (Soft Yellow)
            yellow_cell_format = workbook.add_format({**base_style, 'bg_color': '#FFFFA6'})
            bold_yellow_cell_format = workbook.add_format({**bold_style, 'bg_color': '#FFFFA6'})

            # Dynamic Transaction Column Color Groups (Matching RP2 color coding!)
            sent_cell_format = workbook.add_format({**base_style, 'bg_color': '#729FCF'})      # Soft Blue
            recv_cell_format = workbook.add_format({**base_style, 'bg_color': '#FFFFDE'})      # Light Soft Yellow
            basis_cell_format = workbook.add_format({**base_style, 'bg_color': '#BF819E'})     # Muted Plum/Purple
            hyperlink_format = workbook.add_format({**base_style, 'bg_color': '#FFFFFF', 'font_color': '#2A6099', 'bold': True, 'underline': True})

            # Explicit Number Formatting Strings
            fiat_format_str = f'[$€-1]* #,##0.00;[Red]-[$€-1]* #,##0.00;_(* "-"??_);_(@_)'
            crypto_format_str = '0.00000000'
            percent_format_str = '0.0%'

            # Formatted Cell Variants
            fiat_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFFF', 'num_format': fiat_format_str, 'align': 'right'})
            bold_fiat_fmt = workbook.add_format({**bold_style, 'bg_color': '#FFFFFF', 'num_format': fiat_format_str, 'align': 'right'})
            fiat_yellow_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFA6', 'num_format': fiat_format_str, 'align': 'right'})

            crypto_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFFF', 'num_format': crypto_format_str, 'align': 'right'})
            percent_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFFF', 'num_format': percent_format_str, 'align': 'right'})

            # Formatted Color Column Variants for In-Out Details
            fiat_sent_fmt = workbook.add_format({**base_style, 'bg_color': '#729FCF', 'num_format': fiat_format_str, 'align': 'right'})
            fiat_recv_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFDE', 'num_format': fiat_format_str, 'align': 'right'})
            fiat_basis_fmt = workbook.add_format({**base_style, 'bg_color': '#BF819E', 'num_format': fiat_format_str, 'align': 'right'})
            
            crypto_sent_fmt = workbook.add_format({**base_style, 'bg_color': '#729FCF', 'num_format': crypto_format_str, 'align': 'right'})
            crypto_recv_fmt = workbook.add_format({**base_style, 'bg_color': '#FFFFDE', 'num_format': crypto_format_str, 'align': 'right'})

            for sheet in doc.sheets:
                sheet_name = sheet.name
                safe_sheet_name = sheet_name[:31]
                ws = workbook.add_worksheet(safe_sheet_name)
                ws.hide_gridlines(2) # Show standard gridlines (exactly like LibreOffice)

                # Track column character length for auto-fitting
                col_widths = {}

                # 1. Detect the Header Row
                header_row_idx = -1
                header_keywords = {'activo', 'precio', 'exchange', 'symbol', 'timestamp', 'date', 'crypto', 'fiat', 'amount', 'total', 'summary', 'holder', 'type'}
                
                # Retrieve first 6 rows for header detection
                first_rows = []
                for i, r_obj in enumerate(sheet.rows()):
                    if i >= 6:
                        break
                    first_rows.append(r_obj)

                for r, r_obj in enumerate(first_rows):
                    row_vals = [str(cell.value or "").lower() for cell in r_obj]
                    if any(kw in val for val in row_vals for kw in header_keywords):
                        header_row_idx = r
                        break

                # 2. Iterate and write cells using optimized sheet.rows() generator
                for r, r_obj in enumerate(sheet.rows()):
                    is_header = (r == header_row_idx)
                    is_data = (r > header_row_idx and header_row_idx != -1)

                    # Configure heights comfortable for data rows
                    if is_header:
                        ws.set_row(r, 24)
                    elif is_data:
                        ws.set_row(r, 19)
                    else:
                        ws.set_row(r, 20)

                    # Check if the entire row is a summary / total row
                    row_val_0 = ""
                    if len(r_obj) > 0:
                        row_val_0 = str(r_obj[0].value or "")
                    is_total_row = (is_data and any(kw in row_val_0.lower() for kw in ['total', 'general', 'resumen', 'suma']))

                    # Only iterate over actual columns present in the row
                    ncols = min(len(r_obj), sheet.ncols())
                    for c in range(ncols):
                        cell = r_obj[c]
                        val = cell.value
                        formula = cell.formula

                        # Column length tracking
                        str_val = str(val or "")
                        if formula:
                            str_val = "1234567.89"
                        col_widths[c] = max(col_widths.get(c, 0), len(str_val))

                        # Determine styles
                        if is_header:
                            header_val = str(val or "").lower()
                            if any(kw in header_val for kw in ['precio', 'price', 'unidad', 'entrada']):
                                cell_fmt = yellow_header_format
                            else:
                                cell_fmt = gray_header_format
                        elif not is_data:
                            # Info block styles
                            if r == 0 and c == 0:
                                cell_fmt = title_format
                            elif r == 1 and c == 0:
                                cell_fmt = subtitle_format
                            else:
                                cell_fmt = bold_cell_format if is_total_row or c == 0 else cell_format
                        else:
                            # Data rows styles
                            # Check column properties
                            header_val = ""
                            if header_row_idx != -1 and header_row_idx < len(first_rows):
                                h_row = first_rows[header_row_idx]
                                if c < len(h_row):
                                    header_val = str(h_row[c].value or "").lower()
                            
                            is_pricing_col = any(kw in header_val for kw in ['precio', 'price', 'unidad', 'entrada'])

                            # A. Check for "Entrada-Salida" / "Details" column color coding!
                            is_log_sheet = any(kw in sheet_name.lower() for kw in ['entrada-salida', 'details'])
                            
                            if is_log_sheet:
                                # Column-based dynamic groups in transaction sheets:
                                if c <= 6:
                                    # Sent/Out Details (Soft Blue group)
                                    if any(kw in header_val for kw in ['precio', 'fiat', 'comisi', 'valor']):
                                        cell_fmt = fiat_sent_fmt
                                    elif any(kw in header_val for kw in ['crypto', 'enviado', 'cantidad']):
                                        cell_fmt = crypto_sent_fmt
                                    else:
                                        cell_fmt = sent_cell_format
                                elif c <= 11:
                                    # Received/In Details (Light Yellow group)
                                    if any(kw in header_val for kw in ['precio', 'fiat', 'total', 'comisi']):
                                        cell_fmt = fiat_recv_fmt
                                    elif any(kw in header_val for kw in ['crypto', 'entrada', 'cantidad']):
                                        cell_fmt = crypto_recv_fmt
                                    else:
                                        cell_fmt = recv_cell_format
                                else:
                                    # Tax Details (Soft Purple group)
                                    if any(kw in header_val for kw in ['precio', 'fiat', 'imponible', 'total', 'impuesto']):
                                        cell_fmt = fiat_basis_fmt
                                    else:
                                        cell_fmt = basis_cell_format
                            else:
                                # B. Regular sheets formatting rules
                                if is_total_row:
                                    if is_pricing_col:
                                        cell_fmt = bold_yellow_cell_format
                                    elif any(kw in header_val for kw in ['precio', 'fiat', 'total', 'cost', 'gain', 'loss', 'balance', 'no realizado']):
                                        cell_fmt = bold_fiat_fmt
                                    else:
                                        cell_fmt = bold_cell_format
                                else:
                                    if is_pricing_col:
                                        cell_fmt = yellow_cell_format
                                    elif any(kw in header_val for kw in ['precio', 'fiat', 'total', 'cost', 'gain', 'loss', 'balance', 'no realizado']):
                                        cell_fmt = fiat_yellow_fmt if is_pricing_col else fiat_fmt
                                    elif any(kw in header_val for kw in ['crypto', 'amount', 'fee', 'sent', 'received', 'deficit']):
                                        cell_fmt = crypto_fmt
                                    elif 'peso' in header_val or '%' in header_val:
                                        cell_fmt = percent_fmt
                                    else:
                                        cell_fmt = cell_format

                        # Format hyperlinks differently
                        if formula and 'HYPERLINK' in formula:
                            cell_fmt = hyperlink_format

                        # 3. Write contents/formulas
                        if formula:
                            cleaned_formula = cls.translate_formula(formula)
                            try:
                                ws.write_formula(r, c, cleaned_formula, cell_fmt)
                            except Exception as formula_err:
                                logger.warning("Failed to write formula {} at row {}, col {}: {}", cleaned_formula, r, c, formula_err)
                                if isinstance(val, (int, float)):
                                    ws.write_number(r, c, val, cell_fmt)
                                else:
                                    ws.write(r, c, val, cell_fmt)
                        else:
                            if val is None or val == "":
                                ws.write_blank(r, c, "", cell_fmt)
                            elif isinstance(val, (int, float)):
                                ws.write_number(r, c, val, cell_fmt)
                            else:
                                ws.write(r, c, str(val), cell_fmt)

                # Freeze Panes for perfect scrolling
                if header_row_idx != -1:
                    ws.freeze_panes(header_row_idx + 1, 0)

                # Auto-Fit Columns (minimum 12, max 40)
                for col_idx, max_len in col_widths.items():
                    optimal_width = min(max(max_len + 4, 12), 40)
                    ws.set_column(col_idx, col_idx, optimal_width)

            workbook.close()
            logger.info("Successfully converted ODS to identical styled Excel workbook: {}", xlsx_path.name)
            return True

        except Exception as e:
            logger.error("Failed to convert ODS to premium identical Excel: {}", e)
            logger.exception(e)
            return False

xlsx_converter = XlsxConverter()
